/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author Administrator
 */
public class Calculatorj extends javax.swing.JFrame {
    //setLocationRelativeTo(null);
    
    double NumEnter1;
    double NumEnter2;
    double Result;
    
    String op;
    
    

    /**
     * Creates new form Calculator
     */
    public Calculatorj() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton19 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        Jtxtresult = new javax.swing.JTextField();
        Jbtn4 = new javax.swing.JButton();
        Jbtndiv = new javax.swing.JButton();
        Jbtnplus = new javax.swing.JButton();
        Jbtn1 = new javax.swing.JButton();
        JbtnDot = new javax.swing.JButton();
        Jbtn8 = new javax.swing.JButton();
        Jbtn3 = new javax.swing.JButton();
        Jbtn0 = new javax.swing.JButton();
        Jbtnmul = new javax.swing.JButton();
        Jbtn2 = new javax.swing.JButton();
        Jbtnmin = new javax.swing.JButton();
        JbtnCE = new javax.swing.JButton();
        Jbtn7 = new javax.swing.JButton();
        Jbtnarr = new javax.swing.JButton();
        JbtnC = new javax.swing.JButton();
        JbtnEqual = new javax.swing.JButton();
        Jbtn9 = new javax.swing.JButton();
        Jbtn5 = new javax.swing.JButton();
        Jbtn6 = new javax.swing.JButton();
        Jbtnpm = new javax.swing.JButton();

        jButton19.setText("jButton1");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton13.setText("jButton1");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("jButton3");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton23.setText("jButton1");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jtxtresult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jtxtresult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Jtxtresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtresultActionPerformed(evt);
            }
        });
        getContentPane().add(Jtxtresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 50));

        Jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtn4.setText("4");
        Jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, 50));

        Jbtndiv.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtndiv.setText("/");
        Jbtndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtndivActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtndiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 60, 50));

        Jbtnplus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtnplus.setText("+");
        Jbtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnplusActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtnplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 60, 50));

        Jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtn1.setText("1");
        Jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 60, 50));

        JbtnDot.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDot.setText(".");
        JbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDotActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 60, 50));

        Jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtn8.setText("8");
        Jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, 50));

        Jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtn3.setText("3");
        Jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 60, 50));

        Jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtn0.setText("0");
        Jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 60, 50));

        Jbtnmul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtnmul.setText("*");
        Jbtnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnmulActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtnmul, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 60, 50));

        Jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtn2.setText("2");
        Jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 60, 50));

        Jbtnmin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtnmin.setText("-");
        Jbtnmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnminActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtnmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 60, 50));

        JbtnCE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnCE.setText("CE");
        JbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 50));

        Jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtn7.setText("7");
        Jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 50));

        Jbtnarr.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtnarr.setText("←");
        Jbtnarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnarrActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtnarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 50));

        JbtnC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnC.setText("C");
        JbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, 50));

        JbtnEqual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnEqual.setText("=");
        JbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 60, 50));

        Jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtn9.setText("9");
        Jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 60, 50));

        Jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtn5.setText("5");
        Jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 60, 50));

        Jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtn6.setText("6");
        Jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 60, 50));

        Jbtnpm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtnpm.setText("±");
        Jbtnpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnpmActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtnpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 60, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Enternumber(String S)
    
    {
       String nums=Jtxtresult.getText() + S;
       Jtxtresult.setText(nums);
    }
    
    private void JbtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnplusActionPerformed
          NumEnter1=Double.parseDouble(Jtxtresult.getText());
      Jtxtresult.setText("");
      op="+"; 
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnplusActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void Jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn9ActionPerformed
        // TODO add your handling code here:
        Enternumber("9");
    }//GEN-LAST:event_Jbtn9ActionPerformed

    private void JtxtresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtresultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtresultActionPerformed

    private void Jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn1ActionPerformed
        Enternumber("1");  
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn1ActionPerformed

    private void Jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn4ActionPerformed
        // TODO add your handling code here:
        Enternumber("4");
    }//GEN-LAST:event_Jbtn4ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void Jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn7ActionPerformed
             Enternumber("7");
    }//GEN-LAST:event_Jbtn7ActionPerformed

    private void Jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn8ActionPerformed
        // TODO add your handling code here:
        Enternumber("8");
    }//GEN-LAST:event_Jbtn8ActionPerformed

    private void Jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn5ActionPerformed
      Enternumber("5");     
// TODO add your handling code here:
    }//GEN-LAST:event_Jbtn5ActionPerformed

    private void Jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn6ActionPerformed
        // TODO add your handling code here:
         Enternumber("6");  
    }//GEN-LAST:event_Jbtn6ActionPerformed

    private void Jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn2ActionPerformed
      Enternumber("2");          
// TODO add your handling code here:
    }//GEN-LAST:event_Jbtn2ActionPerformed

    private void Jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn3ActionPerformed
  Enternumber("3");          
// TODO add your handling code here:
    }//GEN-LAST:event_Jbtn3ActionPerformed

    private void Jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn0ActionPerformed
 Enternumber("0");          
// TODO add your handling code here:
    }//GEN-LAST:event_Jbtn0ActionPerformed

    private void JbtnminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnminActionPerformed
         NumEnter1=Double.parseDouble(Jtxtresult.getText());
      Jtxtresult.setText("");
      op="-";
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnminActionPerformed

    private void JbtnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnmulActionPerformed
       NumEnter1=Double.parseDouble(Jtxtresult.getText());
      Jtxtresult.setText("");
      op="*";        
// TODO add your handling code here:
    }//GEN-LAST:event_JbtnmulActionPerformed

    private void JbtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtndivActionPerformed
      NumEnter1=Double.parseDouble(Jtxtresult.getText());
      Jtxtresult.setText("");
      op="/";
// TODO add your handling code here:
    }//GEN-LAST:event_JbtndivActionPerformed

    private void JbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCActionPerformed
        // TODO add your handling code here:
        Jtxtresult.setText("");
    }//GEN-LAST:event_JbtnCActionPerformed

    private void JbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCEActionPerformed
        // TODO add your handling code here:
        Jtxtresult.setText("");
        //string sn;
       // fn=String.valueOf(NumEnter1);
        // sn=String.valueOf(NumEnter2);
         //fn=" ";
        // sn=" ";
    }//GEN-LAST:event_JbtnCEActionPerformed

    private void JbtnpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnpmActionPerformed
        // TODO add your handling code here:
        double  nums =Double.parseDouble(String.valueOf(Jtxtresult.getText()));
        nums=nums * (-1);
        Jtxtresult.setText(String.valueOf(nums));
    }//GEN-LAST:event_JbtnpmActionPerformed

    private void JbtnarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnarrActionPerformed
        // TODO add your handling code here:
        String backspace=null;
        if(Jtxtresult.getText().length() >0)
        {
            StringBuilder sb=new StringBuilder(Jtxtresult.getText());
            sb.deleteCharAt(Jtxtresult.getText().length()-1);
            backspace=sb.toString();
            Jtxtresult.setText(backspace);
            
        }
    }//GEN-LAST:event_JbtnarrActionPerformed

    private void JbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDotActionPerformed
        // TODO add your handling code here:
        if(! Jtxtresult.getText().contains("."));
        {
            Jtxtresult.setText(Jtxtresult.getText() + JbtnDot.getText());
        }
    }//GEN-LAST:event_JbtnDotActionPerformed

    private void JbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnEqualActionPerformed
        // TODO add your handling code here:
        NumEnter2=Double.parseDouble(Jtxtresult.getText());
        if(op=="+")
        {
            Result=NumEnter1+NumEnter2;
            Jtxtresult.setText(String.valueOf(Result));
        }
        else if(op=="-")
        {
            Result=NumEnter1-NumEnter2;
            Jtxtresult.setText(String.valueOf(Result));
        }
       else if(op=="/")
        {
            Result=NumEnter1/NumEnter2;
            Jtxtresult.setText(String.valueOf(Result));
        }
        else if(op=="*")
        {
            Result=NumEnter1*NumEnter2;
            Jtxtresult.setText(String.valueOf(Result));
        }
        
        
    }//GEN-LAST:event_JbtnEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculatorj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculatorj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculatorj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculatorj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculatorj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn0;
    private javax.swing.JButton Jbtn1;
    private javax.swing.JButton Jbtn2;
    private javax.swing.JButton Jbtn3;
    private javax.swing.JButton Jbtn4;
    private javax.swing.JButton Jbtn5;
    private javax.swing.JButton Jbtn6;
    private javax.swing.JButton Jbtn7;
    private javax.swing.JButton Jbtn8;
    private javax.swing.JButton Jbtn9;
    private javax.swing.JButton JbtnC;
    private javax.swing.JButton JbtnCE;
    private javax.swing.JButton JbtnDot;
    private javax.swing.JButton JbtnEqual;
    private javax.swing.JButton Jbtnarr;
    private javax.swing.JButton Jbtndiv;
    private javax.swing.JButton Jbtnmin;
    private javax.swing.JButton Jbtnmul;
    private javax.swing.JButton Jbtnplus;
    private javax.swing.JButton Jbtnpm;
    private javax.swing.JTextField Jtxtresult;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton23;
    // End of variables declaration//GEN-END:variables
}
